### ISSUE TITLE
Cannot compose a Derived component

### ISSUE THREAD

**Issue by kyh** [sannajammeh/tw-classed#111]
**Describe the bug**
Unsure if this is a bug or if I'm doing something incorrectly but I can't seem to compose a new `classed` component from `derived` component

**To Reproduce**
code sample:
```
import { classed, deriveClassed, ComponentProps } from "@tw-classed/react";

const ButtonBase = classed("button", {
  variants: {
    color: {
      red: "red",
      blue: "blue"
    }
  }
});

type ButtonProps = ComponentProps<typeof ButtonBase>;

const DerivedButton = deriveClassed<typeof ButtonBase, ButtonProps>(
  ({ children, ...rest }, ref) => {
    return (
      <ButtonBase {...rest} ref={ref}>
        {children}
      </ButtonBase>
    );
  }
);

const Anchor = classed("a", ButtonBase);
const AnchorWithDerived = classed("a", DerivedButton);

// This works
<Anchor color="blue">Anchor</Anchor>

// This doesn't work
<AnchorWithDerived color="blue">AnchorWithDerived</AnchorWithDerived>
```

Codesandbox: https://codesandbox.io/s/funny-matsumoto-18bjiz?file=/src/App.tsx:700-769

**Expected behavior**
`<AnchorWithDerived color="blue">` should render `<a class="blue">`

**Comment by sannajammeh** [comment]
This is indeed correct behavior. 

```tsx
const AnchorWithDerived = classed("a", DerivedButton);
```

Classed has no internals flow the variants upward, which is required to make the above work. I guess we can call this an anti-pattern.

Essentially what happens here is this:

1. You create a button base
2. You derive it (wrap in forwardRef and provide some typesafe utils)
3. You then class it using `classed("a", DerivedButton)`
4. Step 3 actually creates a new classed component and attempts to extract variants from DerivedButton
5. Since DerivedButton is just a typesafe forwardRef wrapper, it doesn't extract variants from ButtonBase.
6. Thus `AnchorWithDerived` does not do anything.

If you want to produce a default `as` prop you'll need to pass it in your deriveClassed generic.
https://tw-classed.vercel.app/docs/derived-components#experimental-as-manual-prop-support

I see this is a documentation issue on exactly what the `classed()` function does. I will attempt to make a visual of when extraction happens and when rendering happens. The former is what happens here.

**Comment by sannajammeh** [comment]
There's also a type error when deriving a derived component using default as prop, so if you wan't to do that you must cast the ref tag as any:

```tsx
// This works:

const AnchorDefaulted = deriveClassed<typeof DerivedButton, ButtonProps>(
  (props, ref) => <DerivedButton as="a" {...props} ref={ref as any} />
);
```

The deriveClassed api has some rough edges as I didn't expect this advanced usage of it, lets keep this open until its optimised.

Thanks for the issue :)
