### ISSUE TITLE
[Feature request] Default props when creating components

### ISSUE THREAD

**Issue by emmanuelchucks** [sannajammeh/tw-classed#122]
**Is your feature request related to a problem? Please describe.**
When creating a component (e.g. in React Native) would like to have some default props passed to rendered component.

**Describe the solution you'd like**
Something like this would be nice:
```js
const H1 = classed(Text, {
    variants: {
        intent: {
            primary: "text-gray-900",
            secondary: "text-gray-700",
        },
    },
    // ✨ Renders component with these props ✨
    defaultProps: {
        suppressHighlighting: true,
        role: "heading",
        "aria-level": 1,
    },
});
```

**Comment by sannajammeh** [comment]
Thanks for the request. I like the API.

When attaching props, do we allow classed components to inherit? I.e

```tsx
const Text = classed("span", {
    variants: {
        intent: {
            primary: "text-gray-900",
            secondary: "text-gray-700",
        },
    },
    // ✨ Renders component with these props ✨
    defaultProps: {
        suppressHighlighting: true,
        role: "heading",
        "aria-level": 1,
    },
});

const InheritsVariants = classed("h1", Text);
```

In this example, Variants are extracted from `Text` and outputted to a new variant config object for the `h1`. This would be the same as writing the `Text` component twice but with different tag names instead of wrapping two components inside of each other. 

Do we also persist the defaultProps? I think that might lead to UB if people don't read the components.

**Comment by emmanuelchucks** [comment]
IMHO since `defaultVariants` are inherited then it's consistent for `defaultProps` to be inherited too. Both can be easily overwritten anyway when the component is used.

**Comment by sannajammeh** [comment]
Agreed. I think we can implement this, I will try this week and also compare with benchmarks. If performance stays consistent this will be a good feature!

**Comment by emmanuelchucks** [comment]
Any progress on this yet?
