### ISSUE TITLE
Overriding or extending styles using className prop not working when using CSS modules in base styles

### ISSUE THREAD

**Issue by trishagonzales** [sannajammeh/tw-classed#147]
**Describe the bug**
Overriding styles in className prop of a classed component is working when using tailwind in base styles but not when using css modules.
```jsx
import classes from './button.module.css';

function Button() {
   // override with red background
   return <BaseButton className='bg-red-700'>Example</BaseButton>
}

// override is working when using tailwind in base styles
const BaseButton = classed.button('bg-black');

// but not working here when using css modules
const BaseButton = classed.button(classes.button);
```

**To Reproduce**
1. Go to https://stackblitz.com/edit/stackblitz-starters-fgdsvz?file=app%2Fpage.tsx

**Expected behavior**
Override should also work when using css modules

**Environment:**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Node.js Version: 20.9.0

Thanks for this awesome library

**Comment by sannajammeh** [comment]
This is intentional, there is no override happening by default. Everything will be appended to the classname, so you need to use css specificity or `!important` to override.

For Tailwind to override properly you need to use `tailwind-merge`. I have a guide here https://tw-classed.vercel.app/docs/guide/configuring-classed#using-tailwind-merge

For CSS modules you should rely on specificity in the css classes to override

**Comment by trishagonzales** [comment]
thank you
